Repository IPDSnelting/velcom, pull requests merged in 2021-11, with the labels that each got.

#307 Fix publish workflow for location independent image
  .github/workflows/docker-publish.yml
Labels: meta

#305 Fix HTML double escaping in ANSI colored text
  frontend/src/util/Texts.ts
Labels: bug, frontend

#310 Switch to new aaaaaaah vps instance
  .github/workflows/docker-publish.yml
Labels: meta

#312 Unify deployment chaos by using the location independent build
  .github/workflows/docker-publish.yml
  frontend/.env.location-independent
  frontend/.env.production
  frontend/.env.production-aaaaaaah
  frontend/.env.production-kit
  scripts/deploy-aaaaaaah/deploy.sh
  scripts/deploy-aaaaaaah/update-docker-image.sh
Labels: meta

#309 Sort series data in status graph alphabetically
  frontend/src/components/graphs/statuscomparison/StatusComparisonGraph.vue
Labels: frontend

#313 Clarify errors in bench script specification
  docs/bench_repo_specification.md
Labels: meta

#314 Ignore curl's exit code in Aaaaaaah deployment
  .github/workflows/docker-publish.yml
Labels: bug

#316 Improve github bot messages
  backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/committaccess/CommitReadAccess.java
  backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/github/GithubPrInteractor.java
  backend/backend/src/test/java/de/aaaaaaah/velcom/backend/access/committaccess/CommitReadAccessTest.java
Labels: backend
